---
development:
  cloud_name: dplfg2dnt
  api_key: '789323634929554'
  api_secret: ov72CY3kEErfuaq-f6_-752S4nI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dplfg2dnt
  api_key: '789323634929554'
  api_secret: ov72CY3kEErfuaq-f6_-752S4nI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dplfg2dnt
  api_key: '789323634929554'
  api_secret: ov72CY3kEErfuaq-f6_-752S4nI
  enhance_image_tag: true
  static_image_support: false
